name: Analysis
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    name: Code Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extension-csv: openssl,mbstring
          pecl: true

      - name: Install Latest XDebug
        run: |
          wget https://xdebug.org/files/xdebug-2.9.0.tgz
          tar -xvzf xdebug-2.9.0.tgz
          cd xdebug-2.4.0
          phpize && ./configure && make
          sudo cp ./xdebug.so /usr/local/php/modules/xdebug.so
          sudo echo '[xdebug]' >> /etc/php/php.ini
          sudo echo 'zend_extension="/usr/local/php/modules/xdebug.so"' >> /etc/php/php.ini

      - name: Install OpenLDAP
        run: sudo ./tests/resources/openldap/setup.sh

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run Static Analysis
        run: composer run-script analyse

      - name: Run Test Coverage
        run: composer run-script --timeout=0 test-coverage

      - name: Upload Spec Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: FreeDSx-LDAP-Unit

      - name: Upload Integration Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-integration.xml
          name: FreeDSx-LDAP-Integration
